# Generated by Django 4.1.5 on 2023-01-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postladneem_beats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beat",
            name="name",
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
