# Generated by Django 4.1.5 on 2023-01-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postladneem_beats", "0002_alter_beat_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="beat",
            old_name="path",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="beat",
            name="moods",
        ),
        migrations.DeleteModel(
            name="Mood",
        ),
    ]
