# Generated by Django 4.1.5 on 2023-01-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postladneem_beats", "0003_rename_path_beat_file_remove_beat_moods_delete_mood"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beat",
            name="streams",
        ),
        migrations.RemoveField(
            model_name="beat",
            name="uploader",
        ),
    ]
