# Generated by Django 4.1.5 on 2023-01-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postladneem_beats", "0004_remove_beat_streams_remove_beat_uploader"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beat",
            name="duration",
        ),
    ]
