# Generated by Django 4.1.5 on 2023-01-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postladneem_beats", "0005_remove_beat_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beat",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
